python helper_combinexpercent.py --datadirectory "dataset" --from_dataset allenai-art --to_dataset cti-mcq --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset allenai-art --to_dataset dreaddit --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset allenai-art --to_dataset openai-gsm8k --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset allenai-art --to_dataset osai-medmcqa --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset allenai-art --to_dataset sentiment-reasoning --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset allenai-art --to_dataset tmlab-quail --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset cti-mcq --to_dataset allenai-art --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset cti-mcq --to_dataset dreaddit --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset cti-mcq --to_dataset openai-gsm8k --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset cti-mcq --to_dataset osai-medmcqa --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset cti-mcq --to_dataset sentiment-reasoning --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset cti-mcq --to_dataset tmlab-quail --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset dreaddit --to_dataset allenai-art --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset dreaddit --to_dataset cti-mcq --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset dreaddit --to_dataset openai-gsm8k --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset dreaddit --to_dataset osai-medmcqa --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset dreaddit --to_dataset sentiment-reasoning --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset dreaddit --to_dataset tmlab-quail --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset openai-gsm8k --to_dataset allenai-art --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset openai-gsm8k --to_dataset cti-mcq --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset openai-gsm8k --to_dataset dreaddit --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset openai-gsm8k --to_dataset osai-medmcqa --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset openai-gsm8k --to_dataset sentiment-reasoning --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset openai-gsm8k --to_dataset tmlab-quail --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset osai-medmcqa --to_dataset allenai-art --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset osai-medmcqa --to_dataset cti-mcq --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset osai-medmcqa --to_dataset dreaddit --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset osai-medmcqa --to_dataset openai-gsm8k --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset osai-medmcqa --to_dataset sentiment-reasoning --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset osai-medmcqa --to_dataset tmlab-quail --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset sentiment-reasoning --to_dataset allenai-art --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset sentiment-reasoning --to_dataset cti-mcq --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset sentiment-reasoning --to_dataset dreaddit --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset sentiment-reasoning --to_dataset openai-gsm8k --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset sentiment-reasoning --to_dataset osai-medmcqa --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset sentiment-reasoning --to_dataset tmlab-quail --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset tmlab-quail --to_dataset allenai-art --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset tmlab-quail --to_dataset cti-mcq --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset tmlab-quail --to_dataset dreaddit --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset tmlab-quail --to_dataset openai-gsm8k --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset tmlab-quail --to_dataset osai-medmcqa --percent 1
python helper_combinexpercent.py --datadirectory "dataset" --from_dataset tmlab-quail --to_dataset sentiment-reasoning --percent 1
